// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/ptmp.proto

#ifndef PROTOBUF_INCLUDED_src_2fptmp_2eproto
#define PROTOBUF_INCLUDED_src_2fptmp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_src_2fptmp_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2fptmp_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_src_2fptmp_2eproto();
namespace ptmp {
namespace data {
class TPSet;
class TPSetDefaultTypeInternal;
extern TPSetDefaultTypeInternal _TPSet_default_instance_;
class TrigPrim;
class TrigPrimDefaultTypeInternal;
extern TrigPrimDefaultTypeInternal _TrigPrim_default_instance_;
}  // namespace data
}  // namespace ptmp
namespace google {
namespace protobuf {
template<> ::ptmp::data::TPSet* Arena::CreateMaybeMessage<::ptmp::data::TPSet>(Arena*);
template<> ::ptmp::data::TrigPrim* Arena::CreateMaybeMessage<::ptmp::data::TrigPrim>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ptmp {
namespace data {

// ===================================================================

class TrigPrim : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ptmp.data.TrigPrim) */ {
 public:
  TrigPrim();
  virtual ~TrigPrim();

  TrigPrim(const TrigPrim& from);

  inline TrigPrim& operator=(const TrigPrim& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TrigPrim(TrigPrim&& from) noexcept
    : TrigPrim() {
    *this = ::std::move(from);
  }

  inline TrigPrim& operator=(TrigPrim&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TrigPrim& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrigPrim* internal_default_instance() {
    return reinterpret_cast<const TrigPrim*>(
               &_TrigPrim_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TrigPrim* other);
  friend void swap(TrigPrim& a, TrigPrim& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TrigPrim* New() const final {
    return CreateMaybeMessage<TrigPrim>(NULL);
  }

  TrigPrim* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TrigPrim>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TrigPrim& from);
  void MergeFrom(const TrigPrim& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrigPrim* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 tstart = 2;
  bool has_tstart() const;
  void clear_tstart();
  static const int kTstartFieldNumber = 2;
  ::google::protobuf::uint64 tstart() const;
  void set_tstart(::google::protobuf::uint64 value);

  // required uint32 channel = 1;
  bool has_channel() const;
  void clear_channel();
  static const int kChannelFieldNumber = 1;
  ::google::protobuf::uint32 channel() const;
  void set_channel(::google::protobuf::uint32 value);

  // optional uint32 tspan = 3;
  bool has_tspan() const;
  void clear_tspan();
  static const int kTspanFieldNumber = 3;
  ::google::protobuf::uint32 tspan() const;
  void set_tspan(::google::protobuf::uint32 value);

  // optional uint32 adcsum = 4;
  bool has_adcsum() const;
  void clear_adcsum();
  static const int kAdcsumFieldNumber = 4;
  ::google::protobuf::uint32 adcsum() const;
  void set_adcsum(::google::protobuf::uint32 value);

  // optional uint32 adcpeak = 5;
  bool has_adcpeak() const;
  void clear_adcpeak();
  static const int kAdcpeakFieldNumber = 5;
  ::google::protobuf::uint32 adcpeak() const;
  void set_adcpeak(::google::protobuf::uint32 value);

  // optional uint32 flags = 6;
  bool has_flags() const;
  void clear_flags();
  static const int kFlagsFieldNumber = 6;
  ::google::protobuf::uint32 flags() const;
  void set_flags(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ptmp.data.TrigPrim)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 tstart_;
  ::google::protobuf::uint32 channel_;
  ::google::protobuf::uint32 tspan_;
  ::google::protobuf::uint32 adcsum_;
  ::google::protobuf::uint32 adcpeak_;
  ::google::protobuf::uint32 flags_;
  friend struct ::TableStruct_src_2fptmp_2eproto;
};
// -------------------------------------------------------------------

class TPSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ptmp.data.TPSet) */ {
 public:
  TPSet();
  virtual ~TPSet();

  TPSet(const TPSet& from);

  inline TPSet& operator=(const TPSet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TPSet(TPSet&& from) noexcept
    : TPSet() {
    *this = ::std::move(from);
  }

  inline TPSet& operator=(TPSet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TPSet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TPSet* internal_default_instance() {
    return reinterpret_cast<const TPSet*>(
               &_TPSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TPSet* other);
  friend void swap(TPSet& a, TPSet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TPSet* New() const final {
    return CreateMaybeMessage<TPSet>(NULL);
  }

  TPSet* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TPSet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TPSet& from);
  void MergeFrom(const TPSet& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TPSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ptmp.data.TrigPrim tps = 9;
  int tps_size() const;
  void clear_tps();
  static const int kTpsFieldNumber = 9;
  ::ptmp::data::TrigPrim* mutable_tps(int index);
  ::google::protobuf::RepeatedPtrField< ::ptmp::data::TrigPrim >*
      mutable_tps();
  const ::ptmp::data::TrigPrim& tps(int index) const;
  ::ptmp::data::TrigPrim* add_tps();
  const ::google::protobuf::RepeatedPtrField< ::ptmp::data::TrigPrim >&
      tps() const;

  // required uint32 count = 1;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 1;
  ::google::protobuf::uint32 count() const;
  void set_count(::google::protobuf::uint32 value);

  // required uint32 detid = 2;
  bool has_detid() const;
  void clear_detid();
  static const int kDetidFieldNumber = 2;
  ::google::protobuf::uint32 detid() const;
  void set_detid(::google::protobuf::uint32 value);

  // required int64 created = 3;
  bool has_created() const;
  void clear_created();
  static const int kCreatedFieldNumber = 3;
  ::google::protobuf::int64 created() const;
  void set_created(::google::protobuf::int64 value);

  // required uint64 tstart = 4;
  bool has_tstart() const;
  void clear_tstart();
  static const int kTstartFieldNumber = 4;
  ::google::protobuf::uint64 tstart() const;
  void set_tstart(::google::protobuf::uint64 value);

  // optional uint32 tspan = 5;
  bool has_tspan() const;
  void clear_tspan();
  static const int kTspanFieldNumber = 5;
  ::google::protobuf::uint32 tspan() const;
  void set_tspan(::google::protobuf::uint32 value);

  // optional uint32 chanbeg = 6;
  bool has_chanbeg() const;
  void clear_chanbeg();
  static const int kChanbegFieldNumber = 6;
  ::google::protobuf::uint32 chanbeg() const;
  void set_chanbeg(::google::protobuf::uint32 value);

  // optional uint32 chanend = 7;
  bool has_chanend() const;
  void clear_chanend();
  static const int kChanendFieldNumber = 7;
  ::google::protobuf::uint32 chanend() const;
  void set_chanend(::google::protobuf::uint32 value);

  // optional uint32 totaladc = 8;
  bool has_totaladc() const;
  void clear_totaladc();
  static const int kTotaladcFieldNumber = 8;
  ::google::protobuf::uint32 totaladc() const;
  void set_totaladc(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ptmp.data.TPSet)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ptmp::data::TrigPrim > tps_;
  ::google::protobuf::uint32 count_;
  ::google::protobuf::uint32 detid_;
  ::google::protobuf::int64 created_;
  ::google::protobuf::uint64 tstart_;
  ::google::protobuf::uint32 tspan_;
  ::google::protobuf::uint32 chanbeg_;
  ::google::protobuf::uint32 chanend_;
  ::google::protobuf::uint32 totaladc_;
  friend struct ::TableStruct_src_2fptmp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrigPrim

// required uint32 channel = 1;
inline bool TrigPrim::has_channel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TrigPrim::clear_channel() {
  channel_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint32 TrigPrim::channel() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TrigPrim.channel)
  return channel_;
}
inline void TrigPrim::set_channel(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  channel_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TrigPrim.channel)
}

// required uint64 tstart = 2;
inline bool TrigPrim::has_tstart() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TrigPrim::clear_tstart() {
  tstart_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint64 TrigPrim::tstart() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TrigPrim.tstart)
  return tstart_;
}
inline void TrigPrim::set_tstart(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  tstart_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TrigPrim.tstart)
}

// optional uint32 tspan = 3;
inline bool TrigPrim::has_tspan() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TrigPrim::clear_tspan() {
  tspan_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::uint32 TrigPrim::tspan() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TrigPrim.tspan)
  return tspan_;
}
inline void TrigPrim::set_tspan(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  tspan_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TrigPrim.tspan)
}

// optional uint32 adcsum = 4;
inline bool TrigPrim::has_adcsum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TrigPrim::clear_adcsum() {
  adcsum_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint32 TrigPrim::adcsum() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TrigPrim.adcsum)
  return adcsum_;
}
inline void TrigPrim::set_adcsum(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  adcsum_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TrigPrim.adcsum)
}

// optional uint32 adcpeak = 5;
inline bool TrigPrim::has_adcpeak() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TrigPrim::clear_adcpeak() {
  adcpeak_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::uint32 TrigPrim::adcpeak() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TrigPrim.adcpeak)
  return adcpeak_;
}
inline void TrigPrim::set_adcpeak(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  adcpeak_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TrigPrim.adcpeak)
}

// optional uint32 flags = 6;
inline bool TrigPrim::has_flags() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TrigPrim::clear_flags() {
  flags_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::uint32 TrigPrim::flags() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TrigPrim.flags)
  return flags_;
}
inline void TrigPrim::set_flags(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  flags_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TrigPrim.flags)
}

// -------------------------------------------------------------------

// TPSet

// required uint32 count = 1;
inline bool TPSet::has_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TPSet::clear_count() {
  count_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint32 TPSet::count() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.count)
  return count_;
}
inline void TPSet::set_count(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  count_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.count)
}

// required uint32 detid = 2;
inline bool TPSet::has_detid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TPSet::clear_detid() {
  detid_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::uint32 TPSet::detid() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.detid)
  return detid_;
}
inline void TPSet::set_detid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  detid_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.detid)
}

// required int64 created = 3;
inline bool TPSet::has_created() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TPSet::clear_created() {
  created_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 TPSet::created() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.created)
  return created_;
}
inline void TPSet::set_created(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  created_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.created)
}

// required uint64 tstart = 4;
inline bool TPSet::has_tstart() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TPSet::clear_tstart() {
  tstart_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint64 TPSet::tstart() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.tstart)
  return tstart_;
}
inline void TPSet::set_tstart(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  tstart_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.tstart)
}

// optional uint32 tspan = 5;
inline bool TPSet::has_tspan() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TPSet::clear_tspan() {
  tspan_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::uint32 TPSet::tspan() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.tspan)
  return tspan_;
}
inline void TPSet::set_tspan(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  tspan_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.tspan)
}

// optional uint32 chanbeg = 6;
inline bool TPSet::has_chanbeg() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TPSet::clear_chanbeg() {
  chanbeg_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::uint32 TPSet::chanbeg() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.chanbeg)
  return chanbeg_;
}
inline void TPSet::set_chanbeg(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  chanbeg_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.chanbeg)
}

// optional uint32 chanend = 7;
inline bool TPSet::has_chanend() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TPSet::clear_chanend() {
  chanend_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::google::protobuf::uint32 TPSet::chanend() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.chanend)
  return chanend_;
}
inline void TPSet::set_chanend(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  chanend_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.chanend)
}

// optional uint32 totaladc = 8;
inline bool TPSet::has_totaladc() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TPSet::clear_totaladc() {
  totaladc_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::google::protobuf::uint32 TPSet::totaladc() const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.totaladc)
  return totaladc_;
}
inline void TPSet::set_totaladc(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  totaladc_ = value;
  // @@protoc_insertion_point(field_set:ptmp.data.TPSet.totaladc)
}

// repeated .ptmp.data.TrigPrim tps = 9;
inline int TPSet::tps_size() const {
  return tps_.size();
}
inline void TPSet::clear_tps() {
  tps_.Clear();
}
inline ::ptmp::data::TrigPrim* TPSet::mutable_tps(int index) {
  // @@protoc_insertion_point(field_mutable:ptmp.data.TPSet.tps)
  return tps_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ptmp::data::TrigPrim >*
TPSet::mutable_tps() {
  // @@protoc_insertion_point(field_mutable_list:ptmp.data.TPSet.tps)
  return &tps_;
}
inline const ::ptmp::data::TrigPrim& TPSet::tps(int index) const {
  // @@protoc_insertion_point(field_get:ptmp.data.TPSet.tps)
  return tps_.Get(index);
}
inline ::ptmp::data::TrigPrim* TPSet::add_tps() {
  // @@protoc_insertion_point(field_add:ptmp.data.TPSet.tps)
  return tps_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ptmp::data::TrigPrim >&
TPSet::tps() const {
  // @@protoc_insertion_point(field_list:ptmp.data.TPSet.tps)
  return tps_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace ptmp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_src_2fptmp_2eproto
