#+title: Install in UPS Ecosystem

PTMP installs in standard build environments meaning support for
~PKG_CONFIG_PATH~ or explicitly locating dependencies with autoconf like
~--with-*~ options to ~waf configure~.  See ~waf --help~ for details.

The UPS ecosystem locates dependencies via package specific
environment variables following a variety of patterns.  A script is
provided to ease building and installing PTMP in this environment.

* UPS setup

Set up your UPS environment for ZeroMQ, CZMQ and Protobuf.  You might
do something like:

#+BEGIN_EXAMPLE
  $ source /cvmfs/fermilab.opensciencegrid.org/products/artdaq/setup
  $ PRODUCTS=$PRODUCTS:/cvmfs/fermilab.opensciencegrid.org/products/larsoft
  $ setup czmq v4_2_0 -q e15
  $ setup protobuf v3_3_1a -q e15
#+END_EXAMPLE

* Normal installation against UPS products

To install PTMP as a "normal" (non UPS) source package but in a UPS
environment, set up your environment as above and then:

#+BEGIN_EXAMPLE
  $ ./tools/waf-configure-for-ups.sh [/path/to/ptmp/install]
  $ ./waf install
#+END_EXAMPLE

If no installation directory is given to the script then the
installation will go to the ~install/~ directory in the source.

* Installation as UPS product

#+BEGIN_EXAMPLE
  $ ./tools/create-ups-product.sh --help
#+END_EXAMPLE

Example to build ptmp: set up the environment as above and then:

#+BEGIN_EXAMPLE
  $ cd ptmp/
  $ ./tools/create-ups-product.sh /wcdo/lib/ups v00_01_00 e15 czmq protobuf
#+END_EXAMPLE

Example to build ptmp-tcs: 

#+BEGIN_EXAMPLE
  $ setup ptmp vXX_YY_ZZ -q qq
  $ cd ptmp-tcs/
  $ ./tools/create-ups-product.sh /wcdo/lib/ups vAA_BB_CC qq ptmp  
#+END_EXAMPLE

* TODO

Some TODO items for this script:

 - [X] version is taken from git tag, but sometimes UPS product
   builders need to advance their own version, eg to handle build
   level fixes, apply patches, etc.  This is sometimes done by
   appending a letter.  Currently, there is nothing in the script to
   allow that.
   - version is now specified on command line

 - [X] is the ~product_deps~ file needed?  I thought that was an MRB thing
   - it's used to generate the table file

 - [X] it would be nice to parameterize dependencies outside of the
   script so that ~upstools/~ can become a stand-alone repo to be
   included in others (eg, [[https://github.com/brettviren/ptmp-tcs][ptmp-tcs]] like ~waftools/~ is becoming)
   - consolidate ~upstools~ + ~waftools~ into ~tools~ (still ~waftools~ on github)
   - now require ~setup~ of dependencies and listing them on command line

 - [ ] The ZeroMQ related UPS products have a minor break with
   community naming conventions.  If fixed, the script needs updating

   - ~libzmq~ :: name of base package and not ~zeromq~ ("ZeroMQ" is the community name).

   - ~libczmq~ :: name of high level C API and not ~czmq~
